# This file contains values from Cookiecutter

default_context:
  project_name: "steamboat"
  project_description: "A collection of utilities and scripts for microbial bioinformatics"
  organization: "steamboat"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "rpetit3"
  email: "robbie.petit@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
